# Generated by Django 3.2.25 on 2025-03-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='prevention',
            field=models.TextField(blank=True),
        ),
    ]
