# Generated by Django 3.2.25 on 2025-03-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disease_prevention'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='doctors',
            new_name='doctor',
        ),
    ]
