# Generated by Django 3.2.25 on 2025-03-06 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_doctors_disease_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to=settings.AUTH_USER_MODEL),
        ),
    ]
