# Generated by Django 3.2.25 on 2025-03-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_disease_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cause',
            field=models.TextField(blank=True),
        ),
    ]
